import { Outfit, Ovo } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-outfit",
});

const ovo = Ovo({
  subsets: ["latin"],
  weight: "400", // Ovo only has one weight
  variable: "--font-ovo",
});

export const metadata = {
  title: "Portfolio - Tareq Ferdous",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${outfit.className} ${ovo.className} antialiased leading-8 overflow-x-hidden`}
      >
        <div className="w-screen h-screen bg-gradient-to-b from-blue-50 to-red-100">
          {children}
        </div>
      </body>
    </html>
  );
}
